# Generated by Django 4.1 on 2022-11-09 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0004_familyp'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='familyp',
            new_name='Poll',
        ),
        migrations.AlterModelOptions(
            name='poll',
            options={'verbose_name': 'Poll', 'verbose_name_plural': 'Polls'},
        ),
    ]
