# Generated by Django 4.1 on 2022-11-09 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0005_rename_familyp_poll_alter_poll_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Roll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=120)),
                ('DOB', models.DateField()),
            ],
            options={
                'verbose_name': 'Roll',
                'verbose_name_plural': 'Rolls',
            },
        ),
    ]
