# Generated by Django 4.1 on 2022-11-09 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0006_roll'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='img',
            field=models.ImageField(default=True, null=True, upload_to='Photos/'),
        ),
    ]
