# Generated by Django 4.1 on 2022-11-09 17:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0007_alter_post_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Family', models.CharField(default=None, max_length=120)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.AlterField(
            model_name='poll',
            name='Name',
            field=models.CharField(default='None', max_length=120),
        ),
        migrations.CreateModel(
            name='Intial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Surname', models.CharField(max_length=120)),
                ('Category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Categories', to='demo.category')),
            ],
            options={
                'verbose_name': 'Intial',
                'verbose_name_plural': 'Intials',
            },
        ),
    ]
